# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: OpalFalcon
version: '0.0.0'
github: "githubuser/OpalFalcon"
license: MIT
author: "Author name here"
maintainer: "Author name here"
# synopsis: A new Haskeleton package.
# description: OpalFalcon is a new Haskeleton package.
# category: Other

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall -O2 -fexpose-all-unfoldings # -fspecialise-aggressively 

library:
  dependencies:
  - base
  - ghc-prim
  - array
  - vector
  - bytestring
  - JuicyPixels
  - random
  - MonadRandom
  - parallel
  - threads
  - extra
  - containers
  source-dirs: library

executables:
  OpalFalcon:
    source-dirs: executable
    main: Main.hs
    dependencies:
    - base
    - OpalFalcon
    - random
    - array
    - MonadRandom
    - process
    - directory
    - vector
    ghc-options:
    - -threaded
#    - -rtsopts
#    - -with-rtsopts=-N

benchmarks:
  OpalFalcon-benchmarks:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
    - base
    - OpalFalcon
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

tests:
  OpalFalcon-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - base
    - OpalFalcon
    - tasty
    - tasty-hspec
    - HUnit
    - deepseq
    - call-stack
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
