# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: OpalFalcon
version: '0.0.0'
github: "githubuser/OpalFalcon"
license: MIT
author: "Author name here"
maintainer: "Author name here"
# synopsis: A new Haskeleton package.
# description: OpalFalcon is a new Haskeleton package.
# category: Other

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall

library:
  dependencies:
  - base
  - semigroupoids
  - bytestring
  - JuicyPixels
  source-dirs: library

executables:
  OpalFalcon:
    source-dirs: executable
    main: Main.hs
    dependencies:
    - base
    - OpalFalcon
    - vector
    - bytestring
    - JuicyPixels
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

benchmarks:
  OpalFalcon-benchmarks:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
    - base
    - OpalFalcon
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

tests:
  OpalFalcon-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - base
    - OpalFalcon
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
